"""some changes

Revision ID: 290a5d806978
Revises: a83165a78d2c
Create Date: 2025-07-14 19:19:34.883823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '290a5d806978'
down_revision: Union[str, None] = 'a83165a78d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('second_installment', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('third_installment', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'third_installment')
    op.drop_column('orders', 'second_installment')
    op.drop_table('files')
    # ### end Alembic commands ###
