"""adding discount to referralcode and adding seller and discount to order tables

Revision ID: 431e6d3184de
Revises: 2aea803a7b3d
Create Date: 2025-07-13 03:19:22.526900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431e6d3184de'
down_revision: Union[str, None] = '2aea803a7b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('final_price', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'sellers', ['seller_id'], ['id'])
    op.add_column('referral_codes', sa.Column('discount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referral_codes', 'discount')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'final_price')
    op.drop_column('orders', 'discount')
    op.drop_column('orders', 'seller_id')
    # ### end Alembic commands ###
