"""add area code and id number column to users

Revision ID: 523c9e25411a
Revises: f8709ed577d2
Create Date: 2025-07-16 02:45:11.326519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523c9e25411a'
down_revision: Union[str, None] = 'f8709ed577d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default values first
    op.add_column('users', sa.Column('area', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('id_number', sa.String(), nullable=True))
    
    # Update existing records with default values
    op.execute("UPDATE users SET area = 1 WHERE area IS NULL")
    op.execute("UPDATE users SET id_number = '0000000000' WHERE id_number IS NULL")
    
    # Make columns not nullable
    op.alter_column('users', 'area', nullable=False)
    op.alter_column('users', 'id_number', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'id_number')
    op.drop_column('users', 'area')
    # ### end Alembic commands ###
