"""adding grade culomn to referralcode table

Revision ID: 7bc8d78dc20d
Revises: 431e6d3184de
Create Date: 2025-07-13 15:10:49.748180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc8d78dc20d'
down_revision: Union[str, None] = '431e6d3184de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_codes', sa.Column('grade', sa.Enum('GRADE_5', 'GRADE_6', 'GRADE_7', 'GRADE_8', 'GRADE_9', 'GRADE_10', 'GRADE_11', 'GRADE_12', name='gradeenum'), nullable=False))
    op.drop_constraint('referral_codes_user_id_fkey', 'referral_codes', type_='foreignkey')
    op.drop_column('referral_codes', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_codes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('referral_codes_user_id_fkey', 'referral_codes', 'users', ['user_id'], ['id'])
    op.drop_column('referral_codes', 'grade')
    # ### end Alembic commands ###
