"""adding installment and product culomn to referralcode and order table

Revision ID: a83165a78d2c
Revises: 7bc8d78dc20d
Create Date: 2025-07-14 16:41:41.281585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a83165a78d2c'
down_revision: Union[str, None] = '7bc8d78dc20d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    referralcodeproductenum = sa.Enum('ALMAS', 'GRADE_5', 'GRADE_6', 'GRADE_7', 'GRADE_8', 'GRADE_9', name='referralcodeproductenum')
    referralcodeproductenum.create(op.get_bind())
    
    op.add_column('orders', sa.Column('installment', sa.Boolean(), nullable=False))
    op.add_column('orders', sa.Column('first_installment', sa.DateTime(), nullable=True))
    op.add_column('referral_codes', sa.Column('product', referralcodeproductenum, nullable=False))
    op.add_column('referral_codes', sa.Column('installment', sa.Boolean(), nullable=False))
    op.drop_column('referral_codes', 'grade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_codes', sa.Column('grade', postgresql.ENUM('GRADE_5', 'GRADE_6', 'GRADE_7', 'GRADE_8', 'GRADE_9', 'GRADE_10', 'GRADE_11', 'GRADE_12', name='gradeenum'), autoincrement=False, nullable=False))
    op.drop_column('referral_codes', 'installment')
    op.drop_column('referral_codes', 'product')
    op.drop_column('orders', 'first_installment')
    op.drop_column('orders', 'installment')
    
    # Drop the enum type
    referralcodeproductenum = sa.Enum(name='referralcodeproductenum')
    referralcodeproductenum.drop(op.get_bind())
    # ### end Alembic commands ###
